version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 6000:27017
  server:
    build: ./server
    ports:
      - '5221:5221'
    volumes:
      - mongodb_data:/data/db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - DOTNET_RUNNING_IN_CONTAINER=true
    restart: always
    depends_on:
      - mongo
  client:
    build: ./client
    command: npm run start  
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  mongodb_data:
